#ifndef TASKFILEMANAGER_GLOBAL_H
#define TASKFILEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TASKFILEMANAGER_LIB
# define TASKFILEMANAGER_EXPORT Q_DECL_EXPORT
#else
# define TASKFILEMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // TASKFILEMANAGER_GLOBAL_H
