#ifndef FORMULAPAINTER_GLOBAL_H
#define FORMULAPAINTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FORMULAPAINTER_LIB
# define FORMULAPAINTER_EXPORT Q_DECL_EXPORT
#else
# define FORMULAPAINTER_EXPORT Q_DECL_IMPORT
#endif

#endif // FORMULAPAINTER_GLOBAL_H
